### ISSUE TITLE
Add subtitle to udemy course

### ISSUE THREAD

**Issue by Shri2542** [ChrisWonyeobPark/M-HIVE-STM32_drone_programming_course-MH-FC-FW1.0#1]
Hello sir i purchased your course in udemy and it was said that course is available with subtitles and did had for few video then remaining video has no substitle so please look into it. Course name is drone programming

**Comment by ChrisWonyeobPark** [comment]
Hello.
Subtitles of the drone programming course will be continuously added in order but I can't guarantee when it will be finished.
I'm still working on it.
The course will be released for free on Youtube and the source code will be uploaded on GitHub.
So, you don't need to buy the course on Udemy.

**Comment by Shri2542** [comment]
Thank you sir for reply.sir If u don't mind can I ask you doubt .why did
you use two sensor 6dof and 9dof gyro and accelerometer while we can use
only one 6dof gyro and accelerometer sensor for calculating eculer angles
